# Generated by Django 3.2.16 on 2022-12-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addclients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firsname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('dni', models.IntegerField()),
                ('origin', models.CharField(max_length=250)),
                ('destiny', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250, null=True)),
                ('datatime', models.DateField(auto_now=True)),
            ],
        ),
    ]
