# Generated by Django 3.2.16 on 2022-12-27 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcrud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addclients',
            old_name='firsname',
            new_name='firtsname',
        ),
    ]
