# Generated by Django 3.2.16 on 2022-12-27 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcrud', '0002_rename_firsname_addclients_firtsname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addclients',
            old_name='firtsname',
            new_name='firstname',
        ),
    ]
